- name: Install a package using Ansible
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:
  # - name: Install nginx
  #   ansible.builtin.package:
  #     name: nginx
  #     state: present

    - name: Remove the  package
      ansible.builtin.package:
        name: nginx
        state: absent