- name: Install a package using Ansible
  hosts: all
  gather_facts: no
  become: yes
  
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: unInstall nginx
    ansible.builtin.package:
      name: nginx
      state: absent
    tags: mysql
